#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : syntax-highlighting
Version  : 5.83.0
Release  : 43
URL      : https://download.kde.org/stable/frameworks/5.83/syntax-highlighting-5.83.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.83/syntax-highlighting-5.83.0.tar.xz
Summary  : Recorder for internet radios (based on Streamripper)
Group    : Development/Tools
License  : GPL-2.0
Requires: syntax-highlighting-bin = %{version}-%{release}
Requires: syntax-highlighting-data = %{version}-%{release}
Requires: syntax-highlighting-lib = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-kde
BuildRequires : buildreq-meson
BuildRequires : buildreq-qmake
BuildRequires : extra-cmake-modules-data
BuildRequires : perl
BuildRequires : qtbase-dev mesa-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-clrpackages.patch

%description
# Syntax Highlighting
Syntax highlighting engine for Kate syntax definitions
## Table of contents

%package bin
Summary: bin components for the syntax-highlighting package.
Group: Binaries
Requires: syntax-highlighting-data = %{version}-%{release}

%description bin
bin components for the syntax-highlighting package.


%package data
Summary: data components for the syntax-highlighting package.
Group: Data

%description data
data components for the syntax-highlighting package.


%package dev
Summary: dev components for the syntax-highlighting package.
Group: Development
Requires: syntax-highlighting-lib = %{version}-%{release}
Requires: syntax-highlighting-bin = %{version}-%{release}
Requires: syntax-highlighting-data = %{version}-%{release}
Provides: syntax-highlighting-devel = %{version}-%{release}
Requires: syntax-highlighting = %{version}-%{release}

%description dev
dev components for the syntax-highlighting package.


%package lib
Summary: lib components for the syntax-highlighting package.
Group: Libraries
Requires: syntax-highlighting-data = %{version}-%{release}

%description lib
lib components for the syntax-highlighting package.


%prep
%setup -q -n syntax-highlighting-5.83.0
cd %{_builddir}/syntax-highlighting-5.83.0
%patch1 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1628733000
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -Wp,-D_REENTRANT -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -Wl,-sort-common -fasynchronous-unwind-tables -static-libstdc++ -static-libgcc -fexceptions -Wl,--enable-new-dtags -lgcov $PGO_GEN"
export FCFLAGS_GENERATE="-O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -Wp,-D_REENTRANT -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -Wl,-sort-common -fasynchronous-unwind-tables -fexceptions -Wl,--enable-new-dtags -lgcov $PGO_GEN"
export FFLAGS_GENERATE="-O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -Wp,-D_REENTRANT -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -Wl,-sort-common -fasynchronous-unwind-tables -fexceptions -Wl,--enable-new-dtags -lgcov $PGO_GEN"
export CXXFLAGS_GENERATE="-O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -Wp,-D_REENTRANT -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -Wl,-sort-common -fasynchronous-unwind-tables -fexceptions -Wl,--enable-new-dtags -lgcov $PGO_GEN"
export LDFLAGS_GENERATE="-O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -Wp,-D_REENTRANT -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -Wl,-sort-common -fasynchronous-unwind-tables -Wl,--enable-new-dtags -static-libstdc++ -static-libgcc -lgcov $PGO_GEN"
## pgo use
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize
## -Ofast -ffast-math
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
## -pthread -lpthread
## -Wl,-Bsymbolic-functions
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-g3 -ggdb -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc $PGO_USE"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=0
export __GL_SYNC_DISPLAY_DEVICE=DFP-1
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DFP-1
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags_pgo end
if [ ! -f statuspgo ]; then
echo PGO Phase 1
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%cmake ..
make  %{?_smp_mflags}    V=1 VERBOSE=1

make -j1 test V=1 VERBOSE=1
find . -type f,l -not -name '*.gcno' -not -name 'statuspgo*' -delete -print
echo USED > statuspgo
fi
if [ -f statuspgo ]; then
echo PGO Phase 2
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%cmake ..
make  %{?_smp_mflags}    V=1 VERBOSE=1
fi
popd

%install
export SOURCE_DATE_EPOCH=1628733000
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kate-syntax-highlighter

%files data
%defattr(-,root,root,-)
/usr/share/locale/af/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ar/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/az/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/be/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/bg/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/bn/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/br/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/bs/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ca/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/cs/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/cy/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/da/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/de/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/el/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/eo/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/es/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/et/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/eu/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/fa/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/fi/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/fr/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/fy/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ga/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/gl/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/gu/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/he/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/hi/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/hr/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/hsb/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/hu/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ia/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/id/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/is/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/it/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ja/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ka/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/kk/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/km/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ko/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ku/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/lb/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/lt/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/lv/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/mai/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/mk/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ml/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/mr/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ms/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/nb/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/nds/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ne/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/nl/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/nn/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/oc/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/pa/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/pl/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/pt/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ro/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ru/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/se/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/si/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/sk/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/sl/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/sq/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/sr/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/sr@ijekavian/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/sr@ijekavianlatin/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/sr@latin/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/sv/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ta/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/tg/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/th/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/tr/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/ug/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/uk/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/uz/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/uz@cyrillic/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/vi/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/wa/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/xh/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/syntaxhighlighting5_qt.qm
/usr/share/qlogging-categories5/ksyntaxhighlighting.categories
/usr/share/qlogging-categories5/ksyntaxhighlighting.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KSyntaxHighlighting/AbstractHighlighter
/usr/include/KF5/KSyntaxHighlighting/Definition
/usr/include/KF5/KSyntaxHighlighting/DefinitionDownloader
/usr/include/KF5/KSyntaxHighlighting/FoldingRegion
/usr/include/KF5/KSyntaxHighlighting/Format
/usr/include/KF5/KSyntaxHighlighting/Repository
/usr/include/KF5/KSyntaxHighlighting/State
/usr/include/KF5/KSyntaxHighlighting/SyntaxHighlighter
/usr/include/KF5/KSyntaxHighlighting/Theme
/usr/include/KF5/KSyntaxHighlighting/abstracthighlighter.h
/usr/include/KF5/KSyntaxHighlighting/definition.h
/usr/include/KF5/KSyntaxHighlighting/definitiondownloader.h
/usr/include/KF5/KSyntaxHighlighting/foldingregion.h
/usr/include/KF5/KSyntaxHighlighting/format.h
/usr/include/KF5/KSyntaxHighlighting/ksyntaxhighlighting_export.h
/usr/include/KF5/KSyntaxHighlighting/repository.h
/usr/include/KF5/KSyntaxHighlighting/state.h
/usr/include/KF5/KSyntaxHighlighting/syntaxhighlighter.h
/usr/include/KF5/KSyntaxHighlighting/theme.h
/usr/include/KF5/ksyntaxhighlighting_version.h
/usr/lib64/cmake/KF5SyntaxHighlighting/KF5SyntaxHighlightingConfig.cmake
/usr/lib64/cmake/KF5SyntaxHighlighting/KF5SyntaxHighlightingConfigVersion.cmake
/usr/lib64/cmake/KF5SyntaxHighlighting/KF5SyntaxHighlightingTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5SyntaxHighlighting/KF5SyntaxHighlightingTargets.cmake
/usr/lib64/libKF5SyntaxHighlighting.so
/usr/lib64/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5SyntaxHighlighting.so.5
/usr/lib64/libKF5SyntaxHighlighting.so.5.83.0
